import "@/style/globals.css";
import 'aos/dist/aos.css';
import { Inter } from "next/font/google";
import Nav from "@/app/components/Nav";
import Footer from "@/app/components/Foot";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true} >
        <Nav></Nav>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
